# Generated by Django 5.2.4 on 2026-06-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="order_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="rejection_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("out_of_stock", "Out of Stock"),
                    ("ingredients_unavailable", "Ingredients Unavailable"),
                    ("preparation_not_possible", "Preparation Not Possible Today"),
                    ("insufficient_notice", "Insufficient Notice Period"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="spicy_level",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Mild", "Mild"),
                    ("Medium", "Medium"),
                    ("Hot", "Hot"),
                    ("Extra Hot", "Extra Hot"),
                ],
                default="None",
                max_length=10,
            ),
        ),
    ]
