# Generated by Django 5.2.4 on 2026-06-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_vendor_order_count_alter_order_rejection_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalpurchase",
            name="is_reimbursed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="externalpurchase",
            name="reimbursement_proof",
            field=models.FileField(blank=True, null=True, upload_to="reimbursements/"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("prepared", "Prepared"),
                    ("delivered", "Delivered"),
                    ("resolved", "Resolved"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
