# Generated by Django 5.2.4 on 2026-06-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_externalpurchase_is_reimbursed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("partially_accepted", "Partially Accepted"),
                    ("rejected", "Rejected"),
                    ("prepared", "Prepared"),
                    ("delivered", "Delivered"),
                    ("resolved", "Resolved"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
