# Generated by Django 5.2.4 on 2026-08-07 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalpurchase",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases",
                to="core.bill",
            ),
        ),
    ]
