# Generated by Django 5.2.4 on 2026-09-22 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backfill_external_purchase_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='caterer',
            field=models.ForeignKey(limit_choices_to={'role': 'caterer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
