# Generated by Django 5.2.4 on 2026-09-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_billpayment_caterer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='caterer_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_complimentary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
