# Generated by Django 5.2.4 on 2026-09-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_backfill_order_bill_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='orders',
        ),
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.bill'),
        ),
    ]
